# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ujicoding.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import mysql.connector as mc
from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import QTableWidgetItem


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 530)
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 7, 111, 191))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.npm = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.npm.setObjectName("npm")
        self.verticalLayout.addWidget(self.npm)
        self.name = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.name.setObjectName("name")
        self.verticalLayout.addWidget(self.name)
        self.kelas = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.kelas.setObjectName("kelas")
        self.verticalLayout.addWidget(self.kelas)
        self.jurusan = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.jurusan.setObjectName("jurusan")
        self.verticalLayout.addWidget(self.jurusan)
        self.tanggal_lahir = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tanggal_lahir.setObjectName("tanggal_lahir")
        self.verticalLayout.addWidget(self.tanggal_lahir)
        self.tempat_lahir = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.tempat_lahir.setObjectName("tempat_lahir")
        self.verticalLayout.addWidget(self.tempat_lahir)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(130, 10, 261, 191))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.npm_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.npm_edit.setObjectName("npm_edit")
        self.verticalLayout_2.addWidget(self.npm_edit)
        self.name_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.name_edit.setObjectName("name_edit")
        self.verticalLayout_2.addWidget(self.name_edit)
        self.kelas_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.kelas_edit.setObjectName("kelas_edit")
        self.verticalLayout_2.addWidget(self.kelas_edit)
        self.jurusan_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.jurusan_edit.setObjectName("jurusan_edit")
        self.verticalLayout_2.addWidget(self.jurusan_edit)
        self.tanggal_lahir_edit = QtWidgets.QDateEdit(self.verticalLayoutWidget_2)
        self.tanggal_lahir_edit.setCalendarPopup(True)
        self.tanggal_lahir_edit.setObjectName("tanggal_lahir_edit")
        self.verticalLayout_2.addWidget(self.tanggal_lahir_edit)
        self.tempat_lahir_edit = QtWidgets.QLineEdit(self.verticalLayoutWidget_2)
        self.tempat_lahir_edit.setObjectName("tempat_lahir_edit")
        self.verticalLayout_2.addWidget(self.tempat_lahir_edit)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 210, 394, 32))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.insert_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.insert_button.setObjectName("insert_button")
        self.horizontalLayout.addWidget(self.insert_button)
        self.delete_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete_button.setObjectName("delete_button")
        self.horizontalLayout.addWidget(self.delete_button)
        self.update_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.update_button.setObjectName("update_button")
        self.horizontalLayout.addWidget(self.update_button)
        self.load_button = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.load_button.setObjectName("load_button")
        self.horizontalLayout.addWidget(self.load_button)
        self.informationLabel = QtWidgets.QLabel(Form)
        self.informationLabel.setGeometry(QtCore.QRect(10, 250, 381, 16))
        self.informationLabel.setObjectName("informationLabel")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(10, 280, 381, 181))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableWidget = QtWidgets.QTableWidget(self.verticalLayoutWidget_3)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(6)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        self.verticalLayout_3.addWidget(self.tableWidget)
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 470, 381, 41))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.search_edit = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.search_edit.setObjectName("search_edit")
        self.horizontalLayout_2.addWidget(self.search_edit)
        self.search_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.search_button.setObjectName("search_button")
        self.horizontalLayout_2.addWidget(self.search_button)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
        self.insert_button.clicked.connect(self.insert_data)
        self.load_button.clicked.connect(self.load_data)
        self.update_button.clicked.connect(self.update_data)
        self.delete_button.clicked.connect(self.delete_data)
        self.tableWidget.cellClicked.connect(self.get_by_id)
        self.search_button.clicked.connect(self.search_data)

    def insert_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                port="3306",
                user="root",
                password="",
                database="kampus"
            )
            cursor = mydb.cursor()
            npm = self.npm_edit.text()
            name = self.name_edit.text()
            kelas = self.kelas_edit.text()
            jurusan = self.jurusan_edit.text()
            tanggal_lahir = self.tanggal_lahir_edit.date().toString("yyyy-MM-dd")
            tempat_lahir = self.tempat_lahir_edit.text()

            sql = "INSERT INTO mahasiswa (npm, nama, kelas, jurusan, tanggal_lahir, tempat_lahir) VALUES (%s, %s, %s, %s, %s, %s)"
            val = (npm, name, kelas, jurusan, tanggal_lahir, tempat_lahir)
            cursor.execute(sql, val)
            mydb.commit()
            self.informationLabel.setText("Data Mahasiswa Berhasil Disimpan")

            self.npm_edit.setText("")
            self.name_edit.setText("")
            self.kelas_edit.setText("")
            self.jurusan_edit.setText("")
            self.tanggal_lahir_edit.setDate(QtCore.QDate.currentDate())
            self.tempat_lahir_edit.setText("")
        except mc.Error as e:
            self.informationLabel.setText("Data Mahasiswa Gagal Disimpan")

    def load_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                port="3306",
                user="root",
                password="",
                database="kampus"
            )
            mycursor = mydb.cursor()
            mycursor.execute("SELECT * FROM mahasiswa ORDER BY npm ASC")
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.informationLabel.setText("Data Mahasiswa Berhasil Ditampilkan")
        except mc.Error as err:
            self.informationLabel.setText("Data Mahasiswa Gagal DiLoad")

    def update_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                port="3306",
                user="root",
                password="",
                database="kampus"
            )
            cursor = mydb.cursor()
            npm = self.npm_edit.text()
            name = self.name_edit.text()
            kelas = self.kelas_edit.text()
            jurusan = self.jurusan_edit.text()
            tanggal_lahir = self.tanggal_lahir_edit.date().toString("yyyy-MM-dd")
            tempat_lahir = self.tempat_lahir_edit.text()

            sql = "UPDATE mahasiswa SET nama = %s, kelas = %s, jurusan = %s, tanggal_lahir = %s, tempat_lahir = %s WHERE npm = %s"
            val = (name, kelas, jurusan, tanggal_lahir, tempat_lahir, npm)
            cursor.execute(sql, val)
            mydb.commit()
            self.informationLabel.setText("Data Mahasiswa Berhasil Diupdate")

            self.npm_edit.setText("")
            self.name_edit.setText("")
            self.kelas_edit.setText("")
            self.jurusan_edit.setText("")
            self.tanggal_lahir_edit.setDate(QtCore.QDate.currentDate())
            self.tempat_lahir_edit.setText("")
        except mc.Error as e:
            self.informationLabel.setText("Data Mahasiswa Gagal Diupdate")

    def delete_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                port="8889",
                user="root",
                password="",
                database="kampus"
            )
            cursor = mydb.cursor()
            npm = self.npm_edit.text()

            sql = "DELETE FROM mahasiswa WHERE npm = %s"
            val = (npm,)
            cursor.execute(sql, val)
            mydb.commit()
            self.informationLabel.setText("Data Mahasiswa Berhasil Dihapus")

            self.npm_edit.setText("")
            self.name_edit.setText("")
            self.kelas_edit.setText("")
            self.jurusan_edit.setText("")
            self.tanggal_lahir_edit.setDate(QtCore.QDate.currentDate())
            self.tempat_lahir_edit.setText("")
        except mc.Error as e:
            self.informationLabel.setText("Data Mahasiswa Gagal Dihapus")

    def get_by_id(self, row, column):
        npm = self.tableWidget.item(row, 0).text()
        name = self.tableWidget.item(row, 1).text()
        kelas = self.tableWidget.item(row, 2).text()
        jurusan = self.tableWidget.item(row, 3).text()
        tanggal_lahir = self.tableWidget.item(row, 4).text()
        tempat_lahir = self.tableWidget.item(row, 5).text()
        self.npm_edit.setText(npm)
        self.name_edit.setText(name)
        self.kelas_edit.setText(kelas)
        self.jurusan_edit.setText(jurusan)
        self.tanggal_lahir_edit.setDate(QtCore.QDate.fromString(tanggal_lahir, "yyyy-MM-dd"))
        self.tempat_lahir_edit.setText(tempat_lahir)

    def search_data(self):
        try:
            mydb = mc.connect(
                host="localhost",
                port="3306",
                user="root",
                password="",
                database="kampus"
            )
            mycursor = mydb.cursor()
            search_value = self.search_edit.text()
            query = "SELECT * FROM mahasiswa WHERE npm LIKE %s OR nama LIKE %s ORDER BY npm ASC"
            mycursor.execute(query, ('%' + search_value + '%', '%' + search_value + '%'))
            result = mycursor.fetchall()
            self.tableWidget.setRowCount(0)
            for row_number, row_data in enumerate(result):
                self.tableWidget.insertRow(row_number)
                for column_number, data in enumerate(row_data):
                    self.tableWidget.setItem(row_number, column_number, QTableWidgetItem(str(data)))
            self.informationLabel.setText("Data Mahasiswa Berhasil Dicari")
        except mc.Error as err:
            self.informationLabel.setText("Data Mahasiswa Gagal Dicari")

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.npm.setText(_translate("Form", "NPM"))
        self.name.setText(_translate("Form", "Nama"))
        self.kelas.setText(_translate("Form", "Kelas"))
        self.jurusan.setText(_translate("Form", "Jurusan"))
        self.tanggal_lahir.setText(_translate("Form", "Tanggal Lahir"))
        self.tempat_lahir.setText(_translate("Form", "Tempat Lahir"))
        self.tanggal_lahir_edit.setDisplayFormat(_translate("Form", "dd  MMMM yyyy"))
        self.insert_button.setText(_translate("Form", "INSERT"))
        self.delete_button.setText(_translate("Form", "DELETE"))
        self.update_button.setText(_translate("Form", "UPDATE"))
        self.load_button.setText(_translate("Form", "LOAD DATA"))
        self.informationLabel.setText(_translate("Form", "informationLabel"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "NPM"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Nama"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Kelas"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("Form", "Jurusan"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("Form", "Tanggal Lahir"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("Form", "Tempat Lahir"))
        self.search_button.setText(_translate("Form", "Search"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())